# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guild', '0009_auto_20191025_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war', models.IntegerField(choices=[(0, 'woe'), (1, 'woc'), (2, 'zone')], db_index=True)),
                ('data', models.TextField(default='null')),
                ('sort', models.IntegerField(db_index=True, default=0)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_list', related_query_name='party_list', to='guild.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='null')),
                ('sort', models.IntegerField(db_index=True, default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='party.Party')),
                ('war_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_m_list', related_query_name='party_m', to='guild.WarJob')),
            ],
        ),
    ]
