# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='partymember',
            options={'ordering': ['sort']},
        ),
    ]
