# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0009_auto_20191025_0009'),
        ('party', '0002_auto_20191025_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together=set([('guild', 'war', 'sort')]),
        ),
        migrations.AlterUniqueTogether(
            name='partymember',
            unique_together=set([('party', 'sort')]),
        ),
    ]
