# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-01 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_auto_20191101_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='sort',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='sort',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
