# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-04 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.BigIntegerField(db_index=True)),
                ('facebook_token', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
