# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-04 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=1024),
        ),
    ]
