# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rom', '0002_auto_20191009_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='guild/')),
                ('data', models.TextField(blank=True, default=None, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Guild Leader'), (1, 'Guild Vice Leader'), (2, 'Guild Member')], db_index=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rom.CharacterBase')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild.Guild')),
            ],
        ),
    ]
