# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='data',
            field=models.TextField(default='null'),
        ),
    ]
