# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_auto_20191019_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='invite_code',
            field=models.CharField(db_index=True, default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guildmember',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild', related_query_name='guild', to='rom.CharacterBase'),
        ),
        migrations.AlterField(
            model_name='guildmember',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='guild.Guild'),
        ),
    ]
