# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0005_profile'),
        ('guild', '0005_remove_guildmember_line_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', related_query_name='waiting', to='rom.CharacterBase')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', related_query_name='waiting', to='guild.Guild')),
            ],
        ),
    ]
