# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-04 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('image', models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='media/')),
            ],
        ),
    ]
