# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0002_auto_20191004_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
