# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0002_auto_20191009_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbase',
            name='data',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='characterbase',
            name='base_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='characterbase',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='characterjob',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], db_index=True, default=1),
        ),
    ]
