# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 04:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0003_auto_20191019_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterbase',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', related_query_name='base', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='characterjob',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='rom.CharacterBase'),
        ),
        migrations.AlterUniqueTogether(
            name='characterjob',
            unique_together=set([('base', 'job')]),
        ),
    ]
