# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-07 08:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20191004_0937'),
        ('rom', '0004_auto_20191004_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=255)),
                ('base_level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)])),
                ('contribution', models.PositiveIntegerField(default=0)),
                ('gold_medal', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='rom/character/')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rom.CharacterBase')),
            ],
        ),
        migrations.RenameModel(
            old_name='Class',
            new_name='Job',
        ),
        migrations.AddField(
            model_name='characterjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rom.Job'),
        ),
    ]
