# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0007_auto_20191025_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
