# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0008_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='line_contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
